/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.13.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionNueva_imagen;
    QAction *actionAbrir_imagen;
    QAction *actionGuardar;
    QAction *actionGuardar_como;
    QAction *actionCerrar;
    QAction *actionSalir;
    QAction *actionPunto;
    QAction *actionLinea;
    QAction *actionSeleccionar;
    QAction *actionSeleccionar_todo;
    QAction *actionColor_del_pincel;
    QAction *actionPreguntar_si_guardar;
    QAction *actionBrillo_contraste;
    QAction *actionInvertir;
    QAction *actionRotar_90;
    QAction *actionRotar_91;
    QAction *actionMedia_ponderada;
    QAction *actionRotar_180;
    QAction *actionGausiano;
    QAction *actionMedia;
    QAction *actionV_deo_a_video;
    QAction *actionRotar_imagen;
    QAction *actionAcerca_de;
    QAction *actionImagen_media;
    QAction *actionRect_ngulo;
    QAction *actionMediana;
    QAction *actionElipse;
    QAction *actionCopiar_a_nueva;
    QAction *actionCapturar_de_c_mara;
    QAction *actionArco_iris;
    QAction *actionGris;
    QAction *actionRojo;
    QAction *actionVerde;
    QAction *actionAzul;
    QAction *actionEscala_de_grises;
    QAction *actionAjuste_lineal_del_histograma;
    QAction *actionCapturar_de_v_deo;
    QAction *actionBajorrelieve;
    QAction *actionMatiz_saturacion_luminosidad;
    QAction *actionMovimiento;
    QAction *actionNueva_desde_el_portapapeles;
    QAction *actionCopiar_al_portapapeles;
    QAction *actionDeshacer_acci_n;
    QAction *actionPinchar_estirar;
    QAction *actionPerspectiva;
    QAction *actionVer_informaci_n;
    QAction *actionRellenar;
    QAction *actionSuavizar;
    QAction *actionTrazar;
    QAction *actionConvertir_a_color_falso;
    QAction *actionHLS;
    QAction *actionHSV;
    QAction *actionXYZ;
    QAction *actionYUV;
    QAction *actionLab;
    QAction *actionYCrCb;
    QAction *actionMorfolog_a;
    QAction *actionConjunto;
    QAction *actionIndependiente_por_canales;
    QAction *actionRotar_imagen_y_reescalar;
    QAction *actionR_G;
    QAction *actionR_B;
    QAction *actionG_B;
    QAction *actionObtener_espectro;
    QAction *actionPerfilar;
    QAction *actionBuscar_patr_n;
    QAction *actionBalance_de_blancos;
    QAction *actionDetecci_n_de_caras;
    QAction *actionCurva_tonal;
    QWidget *centralWidget;
    QToolButton *toolButton;
    QToolButton *toolButton_2;
    QLabel *label;
    QSlider *horizontalSlider;
    QLabel *label_2;
    QSlider *horizontalSlider_2;
    QToolButton *toolButton_3;
    QToolButton *toolButton_4;
    QToolButton *toolButton_5;
    QToolButton *toolButton_6;
    QPushButton *pushButton;
    QToolButton *toolButton_7;
    QToolButton *toolButton_8;
    QToolButton *toolButton_9;
    QToolButton *toolButton_10;
    QToolButton *toolButton_11;
    QToolButton *toolButton_12;
    QMenuBar *menuBar;
    QMenu *menuArchivo;
    QMenu *menuEdici_n;
    QMenu *menuOpciones;
    QMenu *menuHistograma;
    QMenu *menuHistograma_2D;
    QMenu *menuHerramientas;
    QMenu *menuTransformar;
    QMenu *menuRotar;
    QMenu *menuTransformar_modelo_de_color;
    QMenu *menuVer_histograma_ecualizado;
    QMenu *menuEfectos;
    QMenu *menuSuavizado;
    QMenu *menuV_deo;
    QMenu *menuImagen_a_v_deo;
    QMenu *menuV_deo_a_imagen;
    QMenu *menuAyuda;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(544, 140);
        MainWindow->setMinimumSize(QSize(544, 140));
        MainWindow->setMaximumSize(QSize(544, 140));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/new/prefix1/imagenes/logo.gif"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        actionNueva_imagen = new QAction(MainWindow);
        actionNueva_imagen->setObjectName(QString::fromUtf8("actionNueva_imagen"));
        actionAbrir_imagen = new QAction(MainWindow);
        actionAbrir_imagen->setObjectName(QString::fromUtf8("actionAbrir_imagen"));
        actionGuardar = new QAction(MainWindow);
        actionGuardar->setObjectName(QString::fromUtf8("actionGuardar"));
        actionGuardar_como = new QAction(MainWindow);
        actionGuardar_como->setObjectName(QString::fromUtf8("actionGuardar_como"));
        actionCerrar = new QAction(MainWindow);
        actionCerrar->setObjectName(QString::fromUtf8("actionCerrar"));
        actionSalir = new QAction(MainWindow);
        actionSalir->setObjectName(QString::fromUtf8("actionSalir"));
        actionPunto = new QAction(MainWindow);
        actionPunto->setObjectName(QString::fromUtf8("actionPunto"));
        actionLinea = new QAction(MainWindow);
        actionLinea->setObjectName(QString::fromUtf8("actionLinea"));
        actionSeleccionar = new QAction(MainWindow);
        actionSeleccionar->setObjectName(QString::fromUtf8("actionSeleccionar"));
        actionSeleccionar_todo = new QAction(MainWindow);
        actionSeleccionar_todo->setObjectName(QString::fromUtf8("actionSeleccionar_todo"));
        actionColor_del_pincel = new QAction(MainWindow);
        actionColor_del_pincel->setObjectName(QString::fromUtf8("actionColor_del_pincel"));
        actionPreguntar_si_guardar = new QAction(MainWindow);
        actionPreguntar_si_guardar->setObjectName(QString::fromUtf8("actionPreguntar_si_guardar"));
        actionPreguntar_si_guardar->setCheckable(true);
        actionPreguntar_si_guardar->setChecked(true);
        actionBrillo_contraste = new QAction(MainWindow);
        actionBrillo_contraste->setObjectName(QString::fromUtf8("actionBrillo_contraste"));
        actionInvertir = new QAction(MainWindow);
        actionInvertir->setObjectName(QString::fromUtf8("actionInvertir"));
        actionRotar_90 = new QAction(MainWindow);
        actionRotar_90->setObjectName(QString::fromUtf8("actionRotar_90"));
        actionRotar_91 = new QAction(MainWindow);
        actionRotar_91->setObjectName(QString::fromUtf8("actionRotar_91"));
        actionMedia_ponderada = new QAction(MainWindow);
        actionMedia_ponderada->setObjectName(QString::fromUtf8("actionMedia_ponderada"));
        actionRotar_180 = new QAction(MainWindow);
        actionRotar_180->setObjectName(QString::fromUtf8("actionRotar_180"));
        actionGausiano = new QAction(MainWindow);
        actionGausiano->setObjectName(QString::fromUtf8("actionGausiano"));
        actionMedia = new QAction(MainWindow);
        actionMedia->setObjectName(QString::fromUtf8("actionMedia"));
        actionV_deo_a_video = new QAction(MainWindow);
        actionV_deo_a_video->setObjectName(QString::fromUtf8("actionV_deo_a_video"));
        actionRotar_imagen = new QAction(MainWindow);
        actionRotar_imagen->setObjectName(QString::fromUtf8("actionRotar_imagen"));
        actionAcerca_de = new QAction(MainWindow);
        actionAcerca_de->setObjectName(QString::fromUtf8("actionAcerca_de"));
        actionImagen_media = new QAction(MainWindow);
        actionImagen_media->setObjectName(QString::fromUtf8("actionImagen_media"));
        actionRect_ngulo = new QAction(MainWindow);
        actionRect_ngulo->setObjectName(QString::fromUtf8("actionRect_ngulo"));
        actionMediana = new QAction(MainWindow);
        actionMediana->setObjectName(QString::fromUtf8("actionMediana"));
        actionElipse = new QAction(MainWindow);
        actionElipse->setObjectName(QString::fromUtf8("actionElipse"));
        actionCopiar_a_nueva = new QAction(MainWindow);
        actionCopiar_a_nueva->setObjectName(QString::fromUtf8("actionCopiar_a_nueva"));
        actionCapturar_de_c_mara = new QAction(MainWindow);
        actionCapturar_de_c_mara->setObjectName(QString::fromUtf8("actionCapturar_de_c_mara"));
        actionArco_iris = new QAction(MainWindow);
        actionArco_iris->setObjectName(QString::fromUtf8("actionArco_iris"));
        actionGris = new QAction(MainWindow);
        actionGris->setObjectName(QString::fromUtf8("actionGris"));
        actionRojo = new QAction(MainWindow);
        actionRojo->setObjectName(QString::fromUtf8("actionRojo"));
        actionVerde = new QAction(MainWindow);
        actionVerde->setObjectName(QString::fromUtf8("actionVerde"));
        actionAzul = new QAction(MainWindow);
        actionAzul->setObjectName(QString::fromUtf8("actionAzul"));
        actionEscala_de_grises = new QAction(MainWindow);
        actionEscala_de_grises->setObjectName(QString::fromUtf8("actionEscala_de_grises"));
        actionAjuste_lineal_del_histograma = new QAction(MainWindow);
        actionAjuste_lineal_del_histograma->setObjectName(QString::fromUtf8("actionAjuste_lineal_del_histograma"));
        actionCapturar_de_v_deo = new QAction(MainWindow);
        actionCapturar_de_v_deo->setObjectName(QString::fromUtf8("actionCapturar_de_v_deo"));
        actionBajorrelieve = new QAction(MainWindow);
        actionBajorrelieve->setObjectName(QString::fromUtf8("actionBajorrelieve"));
        actionMatiz_saturacion_luminosidad = new QAction(MainWindow);
        actionMatiz_saturacion_luminosidad->setObjectName(QString::fromUtf8("actionMatiz_saturacion_luminosidad"));
        actionMovimiento = new QAction(MainWindow);
        actionMovimiento->setObjectName(QString::fromUtf8("actionMovimiento"));
        actionNueva_desde_el_portapapeles = new QAction(MainWindow);
        actionNueva_desde_el_portapapeles->setObjectName(QString::fromUtf8("actionNueva_desde_el_portapapeles"));
        actionCopiar_al_portapapeles = new QAction(MainWindow);
        actionCopiar_al_portapapeles->setObjectName(QString::fromUtf8("actionCopiar_al_portapapeles"));
        actionDeshacer_acci_n = new QAction(MainWindow);
        actionDeshacer_acci_n->setObjectName(QString::fromUtf8("actionDeshacer_acci_n"));
        actionPinchar_estirar = new QAction(MainWindow);
        actionPinchar_estirar->setObjectName(QString::fromUtf8("actionPinchar_estirar"));
        actionPerspectiva = new QAction(MainWindow);
        actionPerspectiva->setObjectName(QString::fromUtf8("actionPerspectiva"));
        actionVer_informaci_n = new QAction(MainWindow);
        actionVer_informaci_n->setObjectName(QString::fromUtf8("actionVer_informaci_n"));
        actionRellenar = new QAction(MainWindow);
        actionRellenar->setObjectName(QString::fromUtf8("actionRellenar"));
        actionSuavizar = new QAction(MainWindow);
        actionSuavizar->setObjectName(QString::fromUtf8("actionSuavizar"));
        actionTrazar = new QAction(MainWindow);
        actionTrazar->setObjectName(QString::fromUtf8("actionTrazar"));
        actionConvertir_a_color_falso = new QAction(MainWindow);
        actionConvertir_a_color_falso->setObjectName(QString::fromUtf8("actionConvertir_a_color_falso"));
        actionHLS = new QAction(MainWindow);
        actionHLS->setObjectName(QString::fromUtf8("actionHLS"));
        actionHSV = new QAction(MainWindow);
        actionHSV->setObjectName(QString::fromUtf8("actionHSV"));
        actionXYZ = new QAction(MainWindow);
        actionXYZ->setObjectName(QString::fromUtf8("actionXYZ"));
        actionYUV = new QAction(MainWindow);
        actionYUV->setObjectName(QString::fromUtf8("actionYUV"));
        actionLab = new QAction(MainWindow);
        actionLab->setObjectName(QString::fromUtf8("actionLab"));
        actionYCrCb = new QAction(MainWindow);
        actionYCrCb->setObjectName(QString::fromUtf8("actionYCrCb"));
        actionMorfolog_a = new QAction(MainWindow);
        actionMorfolog_a->setObjectName(QString::fromUtf8("actionMorfolog_a"));
        actionConjunto = new QAction(MainWindow);
        actionConjunto->setObjectName(QString::fromUtf8("actionConjunto"));
        actionIndependiente_por_canales = new QAction(MainWindow);
        actionIndependiente_por_canales->setObjectName(QString::fromUtf8("actionIndependiente_por_canales"));
        actionRotar_imagen_y_reescalar = new QAction(MainWindow);
        actionRotar_imagen_y_reescalar->setObjectName(QString::fromUtf8("actionRotar_imagen_y_reescalar"));
        actionR_G = new QAction(MainWindow);
        actionR_G->setObjectName(QString::fromUtf8("actionR_G"));
        actionR_B = new QAction(MainWindow);
        actionR_B->setObjectName(QString::fromUtf8("actionR_B"));
        actionG_B = new QAction(MainWindow);
        actionG_B->setObjectName(QString::fromUtf8("actionG_B"));
        actionObtener_espectro = new QAction(MainWindow);
        actionObtener_espectro->setObjectName(QString::fromUtf8("actionObtener_espectro"));
        actionPerfilar = new QAction(MainWindow);
        actionPerfilar->setObjectName(QString::fromUtf8("actionPerfilar"));
        actionBuscar_patr_n = new QAction(MainWindow);
        actionBuscar_patr_n->setObjectName(QString::fromUtf8("actionBuscar_patr_n"));
        actionBalance_de_blancos = new QAction(MainWindow);
        actionBalance_de_blancos->setObjectName(QString::fromUtf8("actionBalance_de_blancos"));
        actionDetecci_n_de_caras = new QAction(MainWindow);
        actionDetecci_n_de_caras->setObjectName(QString::fromUtf8("actionDetecci_n_de_caras"));
        actionCurva_tonal = new QAction(MainWindow);
        actionCurva_tonal->setObjectName(QString::fromUtf8("actionCurva_tonal"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        toolButton = new QToolButton(centralWidget);
        toolButton->setObjectName(QString::fromUtf8("toolButton"));
        toolButton->setGeometry(QRect(40, 0, 41, 41));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/new/prefix1/imagenes/abrir.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton->setIcon(icon1);
        toolButton->setIconSize(QSize(32, 32));
        toolButton->setAutoRaise(true);
        toolButton_2 = new QToolButton(centralWidget);
        toolButton_2->setObjectName(QString::fromUtf8("toolButton_2"));
        toolButton_2->setGeometry(QRect(0, 0, 41, 41));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/new/prefix1/imagenes/nuevo.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_2->setIcon(icon2);
        toolButton_2->setIconSize(QSize(32, 32));
        toolButton_2->setAutoRaise(true);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 50, 241, 16));
        label->setStyleSheet(QString::fromUtf8("background-color: rgb(126, 126, 126);"));
        label->setAlignment(Qt::AlignCenter);
        label->setWordWrap(false);
        horizontalSlider = new QSlider(centralWidget);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(10, 70, 241, 21));
        horizontalSlider->setMinimum(2);
        horizontalSlider->setMaximum(120);
        horizontalSlider->setValue(10);
        horizontalSlider->setOrientation(Qt::Horizontal);
        horizontalSlider->setTickPosition(QSlider::TicksBelow);
        horizontalSlider->setTickInterval(10);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(260, 50, 241, 16));
        label_2->setStyleSheet(QString::fromUtf8("background-color: rgb(126, 126, 126);"));
        label_2->setAlignment(Qt::AlignCenter);
        label_2->setWordWrap(false);
        horizontalSlider_2 = new QSlider(centralWidget);
        horizontalSlider_2->setObjectName(QString::fromUtf8("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(260, 70, 241, 21));
        horizontalSlider_2->setMaximum(120);
        horizontalSlider_2->setValue(10);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        horizontalSlider_2->setTickPosition(QSlider::TicksBelow);
        horizontalSlider_2->setTickInterval(10);
        toolButton_3 = new QToolButton(centralWidget);
        toolButton_3->setObjectName(QString::fromUtf8("toolButton_3"));
        toolButton_3->setGeometry(QRect(80, 0, 41, 41));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/new/prefix1/imagenes/guardar.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_3->setIcon(icon3);
        toolButton_3->setIconSize(QSize(32, 32));
        toolButton_3->setAutoRaise(true);
        toolButton_4 = new QToolButton(centralWidget);
        toolButton_4->setObjectName(QString::fromUtf8("toolButton_4"));
        toolButton_4->setGeometry(QRect(130, 0, 41, 41));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/new/prefix1/imagenes/punto.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_4->setIcon(icon4);
        toolButton_4->setIconSize(QSize(32, 32));
        toolButton_4->setCheckable(true);
        toolButton_4->setChecked(true);
        toolButton_4->setAutoExclusive(true);
        toolButton_5 = new QToolButton(centralWidget);
        toolButton_5->setObjectName(QString::fromUtf8("toolButton_5"));
        toolButton_5->setGeometry(QRect(170, 0, 41, 41));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/new/prefix1/imagenes/linea.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_5->setIcon(icon5);
        toolButton_5->setIconSize(QSize(32, 32));
        toolButton_5->setCheckable(true);
        toolButton_5->setAutoExclusive(true);
        toolButton_6 = new QToolButton(centralWidget);
        toolButton_6->setObjectName(QString::fromUtf8("toolButton_6"));
        toolButton_6->setGeometry(QRect(210, 0, 41, 41));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/new/prefix1/imagenes/seleccionar.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_6->setIcon(icon6);
        toolButton_6->setIconSize(QSize(32, 32));
        toolButton_6->setCheckable(true);
        toolButton_6->setAutoExclusive(true);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(500, 0, 41, 41));
        pushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/new/prefix1/imagenes/brushColor.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton->setIcon(icon7);
        pushButton->setIconSize(QSize(64, 64));
        toolButton_7 = new QToolButton(centralWidget);
        toolButton_7->setObjectName(QString::fromUtf8("toolButton_7"));
        toolButton_7->setGeometry(QRect(250, 0, 41, 41));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/new/prefix1/imagenes/rectangulo.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_7->setIcon(icon8);
        toolButton_7->setCheckable(true);
        toolButton_7->setAutoExclusive(true);
        toolButton_8 = new QToolButton(centralWidget);
        toolButton_8->setObjectName(QString::fromUtf8("toolButton_8"));
        toolButton_8->setGeometry(QRect(290, 0, 41, 41));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/new/prefix1/imagenes/elipse.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_8->setIcon(icon9);
        toolButton_8->setCheckable(true);
        toolButton_8->setAutoExclusive(true);
        toolButton_9 = new QToolButton(centralWidget);
        toolButton_9->setObjectName(QString::fromUtf8("toolButton_9"));
        toolButton_9->setGeometry(QRect(330, 0, 41, 41));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/new/prefix1/imagenes/rainbow-icono-rainbow-ico-11563615894jcqy2sfutt.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_9->setIcon(icon10);
        toolButton_9->setCheckable(true);
        toolButton_9->setAutoExclusive(true);
        toolButton_10 = new QToolButton(centralWidget);
        toolButton_10->setObjectName(QString::fromUtf8("toolButton_10"));
        toolButton_10->setGeometry(QRect(370, 0, 41, 41));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/new/prefix1/imagenes/floodFill.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_10->setIcon(icon11);
        toolButton_10->setIconSize(QSize(48, 48));
        toolButton_10->setCheckable(true);
        toolButton_10->setAutoExclusive(true);
        toolButton_11 = new QToolButton(centralWidget);
        toolButton_11->setObjectName(QString::fromUtf8("toolButton_11"));
        toolButton_11->setGeometry(QRect(410, 0, 44, 41));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/new/prefix1/imagenes/suavizado.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_11->setIcon(icon12);
        toolButton_11->setIconSize(QSize(32, 32));
        toolButton_11->setCheckable(true);
        toolButton_11->setAutoExclusive(true);
        toolButton_12 = new QToolButton(centralWidget);
        toolButton_12->setObjectName(QString::fromUtf8("toolButton_12"));
        toolButton_12->setGeometry(QRect(460, 0, 41, 41));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/new/prefix1/imagenes/pencil.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_12->setIcon(icon13);
        toolButton_12->setIconSize(QSize(64, 64));
        toolButton_12->setCheckable(true);
        toolButton_12->setAutoExclusive(true);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 544, 21));
        menuArchivo = new QMenu(menuBar);
        menuArchivo->setObjectName(QString::fromUtf8("menuArchivo"));
        menuEdici_n = new QMenu(menuBar);
        menuEdici_n->setObjectName(QString::fromUtf8("menuEdici_n"));
        menuOpciones = new QMenu(menuEdici_n);
        menuOpciones->setObjectName(QString::fromUtf8("menuOpciones"));
        menuHistograma = new QMenu(menuEdici_n);
        menuHistograma->setObjectName(QString::fromUtf8("menuHistograma"));
        menuHistograma_2D = new QMenu(menuEdici_n);
        menuHistograma_2D->setObjectName(QString::fromUtf8("menuHistograma_2D"));
        menuHerramientas = new QMenu(menuBar);
        menuHerramientas->setObjectName(QString::fromUtf8("menuHerramientas"));
        menuTransformar = new QMenu(menuBar);
        menuTransformar->setObjectName(QString::fromUtf8("menuTransformar"));
        menuRotar = new QMenu(menuTransformar);
        menuRotar->setObjectName(QString::fromUtf8("menuRotar"));
        menuTransformar_modelo_de_color = new QMenu(menuTransformar);
        menuTransformar_modelo_de_color->setObjectName(QString::fromUtf8("menuTransformar_modelo_de_color"));
        menuVer_histograma_ecualizado = new QMenu(menuTransformar);
        menuVer_histograma_ecualizado->setObjectName(QString::fromUtf8("menuVer_histograma_ecualizado"));
        menuEfectos = new QMenu(menuBar);
        menuEfectos->setObjectName(QString::fromUtf8("menuEfectos"));
        menuSuavizado = new QMenu(menuEfectos);
        menuSuavizado->setObjectName(QString::fromUtf8("menuSuavizado"));
        menuV_deo = new QMenu(menuBar);
        menuV_deo->setObjectName(QString::fromUtf8("menuV_deo"));
        menuImagen_a_v_deo = new QMenu(menuV_deo);
        menuImagen_a_v_deo->setObjectName(QString::fromUtf8("menuImagen_a_v_deo"));
        menuV_deo_a_imagen = new QMenu(menuV_deo);
        menuV_deo_a_imagen->setObjectName(QString::fromUtf8("menuV_deo_a_imagen"));
        menuAyuda = new QMenu(menuBar);
        menuAyuda->setObjectName(QString::fromUtf8("menuAyuda"));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuArchivo->menuAction());
        menuBar->addAction(menuEdici_n->menuAction());
        menuBar->addAction(menuHerramientas->menuAction());
        menuBar->addAction(menuTransformar->menuAction());
        menuBar->addAction(menuEfectos->menuAction());
        menuBar->addAction(menuV_deo->menuAction());
        menuBar->addAction(menuAyuda->menuAction());
        menuArchivo->addAction(actionNueva_imagen);
        menuArchivo->addAction(actionAbrir_imagen);
        menuArchivo->addAction(actionNueva_desde_el_portapapeles);
        menuArchivo->addAction(actionCapturar_de_c_mara);
        menuArchivo->addAction(actionCapturar_de_v_deo);
        menuArchivo->addSeparator();
        menuArchivo->addAction(actionGuardar);
        menuArchivo->addAction(actionGuardar_como);
        menuArchivo->addSeparator();
        menuArchivo->addAction(actionCerrar);
        menuArchivo->addAction(actionSalir);
        menuEdici_n->addAction(actionSeleccionar_todo);
        menuEdici_n->addAction(actionCopiar_a_nueva);
        menuEdici_n->addAction(actionDeshacer_acci_n);
        menuEdici_n->addAction(actionCopiar_al_portapapeles);
        menuEdici_n->addAction(actionVer_informaci_n);
        menuEdici_n->addAction(menuHistograma_2D->menuAction());
        menuEdici_n->addSeparator();
        menuEdici_n->addAction(menuOpciones->menuAction());
        menuEdici_n->addAction(menuHistograma->menuAction());
        menuOpciones->addAction(actionColor_del_pincel);
        menuOpciones->addAction(actionPreguntar_si_guardar);
        menuHistograma->addAction(actionGris);
        menuHistograma->addSeparator();
        menuHistograma->addAction(actionRojo);
        menuHistograma->addAction(actionVerde);
        menuHistograma->addAction(actionAzul);
        menuHistograma_2D->addAction(actionR_G);
        menuHistograma_2D->addAction(actionR_B);
        menuHistograma_2D->addAction(actionG_B);
        menuHerramientas->addAction(actionPunto);
        menuHerramientas->addAction(actionLinea);
        menuHerramientas->addAction(actionSeleccionar);
        menuHerramientas->addAction(actionRect_ngulo);
        menuHerramientas->addAction(actionElipse);
        menuHerramientas->addAction(actionArco_iris);
        menuHerramientas->addAction(actionRellenar);
        menuHerramientas->addAction(actionSuavizar);
        menuHerramientas->addAction(actionTrazar);
        menuTransformar->addAction(actionBrillo_contraste);
        menuTransformar->addAction(actionInvertir);
        menuTransformar->addAction(menuRotar->menuAction());
        menuTransformar->addAction(actionMedia_ponderada);
        menuTransformar->addAction(actionCurva_tonal);
        menuTransformar->addAction(actionEscala_de_grises);
        menuTransformar->addAction(actionAjuste_lineal_del_histograma);
        menuTransformar->addAction(actionMatiz_saturacion_luminosidad);
        menuTransformar->addAction(actionPerspectiva);
        menuTransformar->addAction(actionConvertir_a_color_falso);
        menuTransformar->addAction(menuTransformar_modelo_de_color->menuAction());
        menuTransformar->addAction(menuVer_histograma_ecualizado->menuAction());
        menuTransformar->addAction(actionRotar_imagen_y_reescalar);
        menuTransformar->addAction(actionObtener_espectro);
        menuRotar->addAction(actionRotar_90);
        menuRotar->addAction(actionRotar_180);
        menuRotar->addAction(actionRotar_91);
        menuTransformar_modelo_de_color->addAction(actionHLS);
        menuTransformar_modelo_de_color->addAction(actionHSV);
        menuTransformar_modelo_de_color->addAction(actionXYZ);
        menuTransformar_modelo_de_color->addAction(actionYUV);
        menuTransformar_modelo_de_color->addAction(actionLab);
        menuTransformar_modelo_de_color->addAction(actionYCrCb);
        menuVer_histograma_ecualizado->addAction(actionConjunto);
        menuVer_histograma_ecualizado->addAction(actionIndependiente_por_canales);
        menuEfectos->addAction(menuSuavizado->menuAction());
        menuEfectos->addAction(actionBajorrelieve);
        menuEfectos->addAction(actionPinchar_estirar);
        menuEfectos->addAction(actionMorfolog_a);
        menuEfectos->addAction(actionPerfilar);
        menuEfectos->addAction(actionBuscar_patr_n);
        menuEfectos->addAction(actionBalance_de_blancos);
        menuSuavizado->addAction(actionGausiano);
        menuSuavizado->addAction(actionMedia);
        menuSuavizado->addAction(actionMediana);
        menuV_deo->addAction(menuImagen_a_v_deo->menuAction());
        menuV_deo->addAction(menuV_deo_a_imagen->menuAction());
        menuV_deo->addAction(actionV_deo_a_video);
        menuV_deo->addAction(actionDetecci_n_de_caras);
        menuImagen_a_v_deo->addAction(actionRotar_imagen);
        menuV_deo_a_imagen->addAction(actionImagen_media);
        menuV_deo_a_imagen->addAction(actionMovimiento);
        menuAyuda->addAction(actionAcerca_de);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "QFotoPaint4", nullptr));
        actionNueva_imagen->setText(QCoreApplication::translate("MainWindow", "Nueva imagen...", nullptr));
        actionAbrir_imagen->setText(QCoreApplication::translate("MainWindow", "Abrir imagen...", nullptr));
        actionGuardar->setText(QCoreApplication::translate("MainWindow", "Guardar", nullptr));
        actionGuardar_como->setText(QCoreApplication::translate("MainWindow", "Guardar como...", nullptr));
        actionCerrar->setText(QCoreApplication::translate("MainWindow", "Cerrar", nullptr));
        actionSalir->setText(QCoreApplication::translate("MainWindow", "Salir", nullptr));
        actionPunto->setText(QCoreApplication::translate("MainWindow", "Punto", nullptr));
        actionLinea->setText(QCoreApplication::translate("MainWindow", "L\303\255nea", nullptr));
        actionSeleccionar->setText(QCoreApplication::translate("MainWindow", "Seleccionar", nullptr));
        actionSeleccionar_todo->setText(QCoreApplication::translate("MainWindow", "Seleccionar todo", nullptr));
        actionColor_del_pincel->setText(QCoreApplication::translate("MainWindow", "Color del pincel...", nullptr));
        actionPreguntar_si_guardar->setText(QCoreApplication::translate("MainWindow", "Preguntar si guardar", nullptr));
        actionBrillo_contraste->setText(QCoreApplication::translate("MainWindow", "Brillo/Contraste/Gama...", nullptr));
        actionInvertir->setText(QCoreApplication::translate("MainWindow", "Invertir", nullptr));
        actionRotar_90->setText(QCoreApplication::translate("MainWindow", "Rotar 90\302\272", nullptr));
        actionRotar_91->setText(QCoreApplication::translate("MainWindow", "Rotar 270\302\272", nullptr));
        actionMedia_ponderada->setText(QCoreApplication::translate("MainWindow", "Media ponderada...", nullptr));
        actionRotar_180->setText(QCoreApplication::translate("MainWindow", "Rotar 180\302\272", nullptr));
        actionGausiano->setText(QCoreApplication::translate("MainWindow", "Gausiano...", nullptr));
        actionMedia->setText(QCoreApplication::translate("MainWindow", "Media...", nullptr));
        actionV_deo_a_video->setText(QCoreApplication::translate("MainWindow", "V\303\255deo a video", nullptr));
        actionRotar_imagen->setText(QCoreApplication::translate("MainWindow", "Rotar imagen...", nullptr));
        actionAcerca_de->setText(QCoreApplication::translate("MainWindow", "Acerca de...", nullptr));
        actionImagen_media->setText(QCoreApplication::translate("MainWindow", "Imagen media...", nullptr));
        actionRect_ngulo->setText(QCoreApplication::translate("MainWindow", "Rect\303\241ngulo", nullptr));
        actionMediana->setText(QCoreApplication::translate("MainWindow", "Mediana", nullptr));
        actionElipse->setText(QCoreApplication::translate("MainWindow", "Elipse", nullptr));
        actionCopiar_a_nueva->setText(QCoreApplication::translate("MainWindow", "Copiar a nueva", nullptr));
        actionCapturar_de_c_mara->setText(QCoreApplication::translate("MainWindow", "Capturar de c\303\241mara...", nullptr));
        actionArco_iris->setText(QCoreApplication::translate("MainWindow", "Arcoiris", nullptr));
        actionGris->setText(QCoreApplication::translate("MainWindow", "Gris", nullptr));
        actionRojo->setText(QCoreApplication::translate("MainWindow", "Rojo", nullptr));
        actionVerde->setText(QCoreApplication::translate("MainWindow", "Verde", nullptr));
        actionAzul->setText(QCoreApplication::translate("MainWindow", "Azul", nullptr));
        actionEscala_de_grises->setText(QCoreApplication::translate("MainWindow", "Escala de color", nullptr));
        actionAjuste_lineal_del_histograma->setText(QCoreApplication::translate("MainWindow", "Ajuste lineal del histograma...", nullptr));
        actionCapturar_de_v_deo->setText(QCoreApplication::translate("MainWindow", "Capturar de v\303\255deo...", nullptr));
        actionBajorrelieve->setText(QCoreApplication::translate("MainWindow", "Bajorrelieve..", nullptr));
        actionMatiz_saturacion_luminosidad->setText(QCoreApplication::translate("MainWindow", "Matiz/saturacion/luminosidad", nullptr));
        actionMovimiento->setText(QCoreApplication::translate("MainWindow", "Movimiento..", nullptr));
        actionNueva_desde_el_portapapeles->setText(QCoreApplication::translate("MainWindow", "Nueva desde el portapapeles", nullptr));
        actionCopiar_al_portapapeles->setText(QCoreApplication::translate("MainWindow", "Copiar al portapapeles", nullptr));
        actionDeshacer_acci_n->setText(QCoreApplication::translate("MainWindow", "Deshacer acci\303\263n", nullptr));
        actionPinchar_estirar->setText(QCoreApplication::translate("MainWindow", "Pinchar/estirar", nullptr));
        actionPerspectiva->setText(QCoreApplication::translate("MainWindow", "Perspectiva...", nullptr));
        actionVer_informaci_n->setText(QCoreApplication::translate("MainWindow", "Ver informaci\303\263n", nullptr));
        actionRellenar->setText(QCoreApplication::translate("MainWindow", "Rellenar", nullptr));
        actionSuavizar->setText(QCoreApplication::translate("MainWindow", "Suavizar", nullptr));
        actionTrazar->setText(QCoreApplication::translate("MainWindow", "Trazar", nullptr));
        actionConvertir_a_color_falso->setText(QCoreApplication::translate("MainWindow", "Convertir a color falso", nullptr));
        actionHLS->setText(QCoreApplication::translate("MainWindow", "HLS", nullptr));
        actionHSV->setText(QCoreApplication::translate("MainWindow", "HSV", nullptr));
        actionXYZ->setText(QCoreApplication::translate("MainWindow", "XYZ", nullptr));
        actionYUV->setText(QCoreApplication::translate("MainWindow", "YUV", nullptr));
        actionLab->setText(QCoreApplication::translate("MainWindow", "Lab", nullptr));
        actionYCrCb->setText(QCoreApplication::translate("MainWindow", "YCrCb", nullptr));
        actionMorfolog_a->setText(QCoreApplication::translate("MainWindow", "Morfolog\303\255a", nullptr));
        actionConjunto->setText(QCoreApplication::translate("MainWindow", "Conjunto", nullptr));
        actionIndependiente_por_canales->setText(QCoreApplication::translate("MainWindow", "Independiente por canales", nullptr));
        actionRotar_imagen_y_reescalar->setText(QCoreApplication::translate("MainWindow", "Rotar imagen y reescalar", nullptr));
        actionR_G->setText(QCoreApplication::translate("MainWindow", "R-G", nullptr));
        actionR_B->setText(QCoreApplication::translate("MainWindow", "R-B", nullptr));
        actionG_B->setText(QCoreApplication::translate("MainWindow", "G-B", nullptr));
        actionObtener_espectro->setText(QCoreApplication::translate("MainWindow", "Obtener espectro", nullptr));
        actionPerfilar->setText(QCoreApplication::translate("MainWindow", "Perfilar", nullptr));
        actionBuscar_patr_n->setText(QCoreApplication::translate("MainWindow", "Buscar patr\303\263n", nullptr));
        actionBalance_de_blancos->setText(QCoreApplication::translate("MainWindow", "Balance de blancos", nullptr));
        actionDetecci_n_de_caras->setText(QCoreApplication::translate("MainWindow", "Detecci\303\263n de caras", nullptr));
        actionCurva_tonal->setText(QCoreApplication::translate("MainWindow", "Curva tonal...", nullptr));
        toolButton->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        toolButton_2->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffffff;\">Radio del pincel</span></p></body></html>", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ffffff;\">Suavizado del pincel</span></p></body></html>", nullptr));
        toolButton_3->setText(QString());
        toolButton_4->setText(QString());
        toolButton_5->setText(QString());
        toolButton_6->setText(QString());
        pushButton->setText(QString());
        toolButton_7->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        toolButton_8->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        toolButton_9->setText(QCoreApplication::translate("MainWindow", "Arcoiris", nullptr));
        toolButton_10->setText(QCoreApplication::translate("MainWindow", "Rellenar", nullptr));
        toolButton_11->setText(QCoreApplication::translate("MainWindow", "Suavizar", nullptr));
        toolButton_12->setText(QCoreApplication::translate("MainWindow", "L\303\241piz", nullptr));
        menuArchivo->setTitle(QCoreApplication::translate("MainWindow", "Archivo", nullptr));
        menuEdici_n->setTitle(QCoreApplication::translate("MainWindow", "Edici\303\263n", nullptr));
        menuOpciones->setTitle(QCoreApplication::translate("MainWindow", "Opciones", nullptr));
        menuHistograma->setTitle(QCoreApplication::translate("MainWindow", "Histograma", nullptr));
        menuHistograma_2D->setTitle(QCoreApplication::translate("MainWindow", "Histograma 2D", nullptr));
        menuHerramientas->setTitle(QCoreApplication::translate("MainWindow", "Herramientas", nullptr));
        menuTransformar->setTitle(QCoreApplication::translate("MainWindow", "Transformar", nullptr));
        menuRotar->setTitle(QCoreApplication::translate("MainWindow", "Rotar", nullptr));
        menuTransformar_modelo_de_color->setTitle(QCoreApplication::translate("MainWindow", "Transformar modelo de color", nullptr));
        menuVer_histograma_ecualizado->setTitle(QCoreApplication::translate("MainWindow", "Ver histograma ecualizado", nullptr));
        menuEfectos->setTitle(QCoreApplication::translate("MainWindow", "Efectos", nullptr));
        menuSuavizado->setTitle(QCoreApplication::translate("MainWindow", "Suavizado", nullptr));
        menuV_deo->setTitle(QCoreApplication::translate("MainWindow", "V\303\255deo", nullptr));
        menuImagen_a_v_deo->setTitle(QCoreApplication::translate("MainWindow", "Imagen a v\303\255deo", nullptr));
        menuV_deo_a_imagen->setTitle(QCoreApplication::translate("MainWindow", "V\303\255deo a imagen", nullptr));
        menuAyuda->setTitle(QCoreApplication::translate("MainWindow", "Ayuda", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
